### ISSUE TITLE
IE11 problems?

### ISSUE THREAD

**Issue by raphaelarias** [ejfrancis/Vuex-Alt#3]
I think this package is awesome!

We are using it in all our projects. But one things we saw is that our app does not work on IE11, and apparently the reason are that we have arrow functions that are not being transpiled, and this arrow functions seem to be from this package. Would you know if that's plausible?

Thanks

**Comment by ejfrancis** [comment]
@raphaelarias yes the `dist` build does include arrow functions. I'll change the babel config to transpile for legacy browsers

**Comment by ejfrancis** [comment]
@raphaelarias this is released in 0.0.8. Let me know if you have any more issues, and thanks for using the package!
